pod 'SDWebImage'
pod 'AFNetworking', '~> 2.5.0'
pod 'SVProgressHUD'
pod 'PayPal-iOS-SDK', '~> 2.4.2'
pod 'UICKeyChainStore', '~> 1.0.4'
pod 'Stripe', '2.2.0'
pod 'Stripe/ApplePay'
pod 'OLImageEditor'
pod 'UIImageView+FadeIn'
pod 'LXReorderableCollectionViewFlowLayout'
