ignore:
  - "Kite-SDK/PSPrintSDK/RMImageCropper"
  - "Kite-SDK/PSPrintSDK/QREncoder"
  - "Kite-SDK/PSPrintSDK/AppDelegate*"
  - "Kite-SDK/PSPrintSDK/AssetDataSource*"
  - "Kite-SDK/PSPrintSDK/CI-ViewController*"
  - "Kite-SDK/PSPrintSDK/ViewController*"
  - "Kite-SDK/PSPrintSDK/CustomAssetCollectionDataSource*"
  - "Kite-SDK/PSPrintSDK/LXReorderableCollectionViewFlowLayout*"
  - "Kite-SDK/PSPrintSDK/OLAnimation*"
  - "Kite-SDK/PSPrintSDK/OLFlipEnumerations*"
  - "Kite-SDK/PSPrintSDK/OLFlipTransition*"
  - "Kite-SDK/PSPrintSDK/OLFlipViewController*"
  - "Kite-SDK/PSPrintSDK/OLTransition*"
  - "Kite-SDK/PSPrintSDK/OLTransitionEnumerations*"
  - "Kite-SDK/PSPrintSDK/OLMarkdownParser*"
  - "Kite-SDK/PSPrintSDK/OLCircularProgressView*"
  - "Kite-SDK/PSPrintSDK/OLIndefiniteAnimatedView*"
  - "Kite-SDK/PSPrintSDK/OLProgressHUD*"
  - "Kite-SDK/PSPrintSDK/OLRadialGradientLayer*"
  - "Kite-SDK/PSPrintSDK/NSURL+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSString+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSData+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLKeyChainStore*"
  - "Kite-SDK/PSPrintSDK/main.m"